version: "3.7"
services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: devs12345/web_gd_backend
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    networks:
      - laravel-network

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 8800:80
    volumes:
      - ./:/var/www/html/
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

